version: '3.8'

services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/app # 開発環境用
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ANOTHER_ENV=${ANOTHER_ENV}
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - skillnavigator_network
    
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules  
    ports:
      - "3000:3000"
    # restart: always 
    #command: sh -c "npm run dev"  入れようか迷ってます環境開発用
    networks:
      - skillnavigator_network


  db:
    image: postgres:15
    container_name: skillnavigator-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Dockerホストのポート5433がコンテナのポート5432にマッピングされる
    ports:
      - 5433:5432
    networks:
      - skillnavigator_network
      
networks:
  skillnavigator_network:
    driver: bridge

volumes:
  postgres_data:
  node_modules: