"""Initial migration

Revision ID: 0b04a77e991f
Revises: f74dc175abfb
Create Date: 2024-01-08 14:52:18.816404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b04a77e991f'
down_revision: Union[str, None] = 'f74dc175abfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('llm_answers_course_details_id_fkey', 'llm_answers', type_='foreignkey')
    op.drop_column('llm_answers', 'course_details_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_answers', sa.Column('course_details_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('llm_answers_course_details_id_fkey', 'llm_answers', 'course_details', ['course_details_id'], ['course_details_id'])
    # ### end Alembic commands ###
