"""Initial migration

Revision ID: 2946053dc67b
Revises: 76cd9bedfcba
Create Date: 2024-01-05 13:50:55.042217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2946053dc67b'
down_revision: Union[str, None] = '76cd9bedfcba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CompletedRecord',
    sa.Column('completedrecord_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('completed_flg', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('completedrecord_id')
    )
    op.create_index(op.f('ix_CompletedRecord_completedrecord_id'), 'CompletedRecord', ['completedrecord_id'], unique=False)
    op.create_table('Record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.Column('dates', sa.DateTime(), nullable=False),
    sa.Column('content_name_A', sa.String(length=50), nullable=True),
    sa.Column('content_name_B', sa.String(length=50), nullable=True),
    sa.Column('study_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_Record_record_id'), 'Record', ['record_id'], unique=False)
    op.alter_column('course_details', 'course_level',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_setting', 'current_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('users', sa.Column('user_setting_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_setting', ['user_setting_id'], ['user_setting_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_setting_id')
    op.alter_column('user_setting', 'current_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('course_details', 'course_level',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_Record_record_id'), table_name='Record')
    op.drop_table('Record')
    op.drop_index(op.f('ix_CompletedRecord_completedrecord_id'), table_name='CompletedRecord')
    op.drop_table('CompletedRecord')
    # ### end Alembic commands ###
