"""initial migration

Revision ID: a93bae487c6b
Revises: 
Create Date: 2024-01-02 15:49:22.871221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93bae487c6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_details',
    sa.Column('course_details_id', sa.Integer(), nullable=False),
    sa.Column('course_level', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('course_details_id'),
    sa.UniqueConstraint('course_level')
    )
    op.create_index(op.f('ix_course_details_course_details_id'), 'course_details', ['course_details_id'], unique=False)
    op.create_table('user_setting',
    sa.Column('user_setting_id', sa.Integer(), nullable=False),
    sa.Column('current_date', sa.DateTime(), nullable=True),
    sa.Column('target_period', sa.String(length=10), nullable=False),
    sa.Column('learning_history', sa.String(length=30), nullable=False),
    sa.Column('target_level', sa.String(length=30), nullable=False),
    sa.Column('monday_study_time', sa.Integer(), nullable=False),
    sa.Column('tuesday_study_time', sa.Integer(), nullable=False),
    sa.Column('wednesday_study_time', sa.Integer(), nullable=False),
    sa.Column('thursday_study_time', sa.Integer(), nullable=False),
    sa.Column('friday_study_time', sa.Integer(), nullable=False),
    sa.Column('saturday_study_time', sa.Integer(), nullable=False),
    sa.Column('sunday_study_time', sa.Integer(), nullable=False),
    sa.Column('motivation_statement', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('user_setting_id')
    )
    op.create_index(op.f('ix_user_setting_user_setting_id'), 'user_setting', ['user_setting_id'], unique=False)
    op.create_table('llm_answers',
    sa.Column('llm_answers_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_setting_id', sa.Integer(), nullable=True),
    sa.Column('course_details_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_details_id'], ['course_details.course_details_id'], ),
    sa.ForeignKeyConstraint(['user_setting_id'], ['user_setting.user_setting_id'], ),
    sa.PrimaryKeyConstraint('llm_answers_id')
    )
    op.create_index(op.f('ix_llm_answers_llm_answers_id'), 'llm_answers', ['llm_answers_id'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_llm_answers_llm_answers_id'), table_name='llm_answers')
    op.drop_table('llm_answers')
    op.drop_index(op.f('ix_user_setting_user_setting_id'), table_name='user_setting')
    op.drop_table('user_setting')
    op.drop_index(op.f('ix_course_details_course_details_id'), table_name='course_details')
    op.drop_table('course_details')
    # ### end Alembic commands ###
