"""Initial migration

Revision ID: bd45633ec089
Revises: 42248ae4015d
Create Date: 2023-12-27 13:18:20.956045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd45633ec089'
down_revision: Union[str, None] = '42248ae4015d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_details', sa.Column('course_level', sa.String(length=30), nullable=True))
    op.drop_constraint('course_details_level_key', 'course_details', type_='unique')
    op.create_unique_constraint(None, 'course_details', ['course_level'])
    op.drop_column('course_details', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_details', sa.Column('level', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course_details', type_='unique')
    op.create_unique_constraint('course_details_level_key', 'course_details', ['level'])
    op.drop_column('course_details', 'course_level')
    # ### end Alembic commands ###
