"""initial

Revision ID: d2dc45cd6168
Revises: 
Create Date: 2023-12-25 06:16:28.999993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2dc45cd6168'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User Setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_period', sa.String(length=10), nullable=False),
    sa.Column('learning_history', sa.String(length=30), nullable=False),
    sa.Column('target_level', sa.String(length=30), nullable=False),
    sa.Column('monday_study_time', sa.Integer(), nullable=False),
    sa.Column('tuesday_study_time', sa.Integer(), nullable=False),
    sa.Column('wednesday_study_time', sa.Integer(), nullable=False),
    sa.Column('thursday_study_time', sa.Integer(), nullable=False),
    sa.Column('friday_study_time', sa.Integer(), nullable=False),
    sa.Column('saturday_study_time', sa.Integer(), nullable=False),
    sa.Column('sunday_study_time', sa.Integer(), nullable=False),
    sa.Column('motivation_statement', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User Setting_id'), 'User Setting', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User Setting_id'), table_name='User Setting')
    op.drop_table('User Setting')
    # ### end Alembic commands ###
