"""Initial migration

Revision ID: f2d31025c847
Revises: 2946053dc67b
Create Date: 2024-01-05 05:24:04.443022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d31025c847'
down_revision: Union[str, None] = '2946053dc67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_user_setting_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'user_setting_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_setting_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_user_setting_id_fkey', 'users', 'user_setting', ['user_setting_id'], ['user_setting_id'])
    # ### end Alembic commands ###
